server:
  port: 8080
  ssl:
    key-store: classpath:keystore.p12  # 인증서 파일 경로
    key-store-type: PKCS12
    key-store-password: springbackendssl

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i9b107.p.ssafy.io:3366/ting_db?serverTimezone=Asia/Seoul
    username: ssafy_b107
    password: 1q2w3e4r-ssafy-b107-ting

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # 이메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: haha429315@gmail.com
    password: qaagqekaqjdchlte
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # mongoDB
  data:
    mongodb:
      host: i9b107.p.ssafy.io
      port: 5158
      database: admin
      authentication-database: admin
      auto-index-creation: true
      username: ting-mongo
      password: 1q2w3e4r-ting-mongo

  # 채팅
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: false
#  freemarker:
#    cache: false

jwt:
  secretKey: JwtSecretKeyForShortDate

openvidu:
  url: https://i9b107.p.ssafy.io
  secret: ting-openvidu-1q2w

ncloud:
  sens:
    serviceId: ncp:sms:kr:307962030868:ting
    accessKeyId: BbrWAOXUJtjrBbP71wP3
    secretKey: bdVJFqzAnewfwK86dsM6llnerPrTwQOmbX6ts4kn
    senderPhone: 01050659767

# profile 이미지 파일경로
file:
  path: /app/profile

# natural language api
cloud:
  gcp:
    credentials:
      location: classpath:service-account-key.json

payment:
  kakaopay:
    admin:
      key: 68c2aade4f26ed122b7aa651eedaf2fa
    cid: TC0ONETIME
    url:
      ready: https://kapi.kakao.com/v1/payment/ready
      approve: https://kapi.kakao.com/v1/payment/approve
    redirectUrl:
      approvalRedirectUrl: /payment/kakaoPaySuccess
      cancelRedirectUrl: /payment/kakaoPayCancel
      failRedirectUrl: /payment/kakaoPayFail
