server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i9b107.p.ssafy.io:3366/ting_db?serverTimezone=Asia/Seoul
    username: ssafy_b107
    password: 1q2w3e4r-ssafy-b107-ting

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # 이메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: haha429315@gmail.com
    password: qaagqekaqjdchlte
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secretKey: JwtSecretKeyForShortDate